// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SensorData.Data;

#nullable disable

namespace SensorData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SensorData.models.SensorDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("Battery")
                        .HasColumnType("smallint");

                    b.Property<int>("Co2")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastComDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Light")
                        .HasColumnType("integer");

                    b.Property<int>("Noise")
                        .HasColumnType("integer");

                    b.Property<int>("POISensorId")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("LastComDate")
                        .HasDatabaseName("IX_SensorData_LastComDate");

                    b.HasIndex("POISensorId")
                        .HasDatabaseName("IX_SensorData_POISensorId");

                    b.HasIndex("POISensorId", "LastComDate")
                        .HasDatabaseName("IX_SensorData_POISensorId_LastComDate");

                    b.ToTable("SensorData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
